version:     "001--05-Sep-2021"
copyright:   "2021-2021"
description:
  This is a
  OS212 GitHub Page 
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "My Log"
  link:      "/TXT/mylog.txt"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Key"
  link:      "/TXT/mypubkey.txt"
- navbar:    "Rank"
  link:      "/TXT/myrank.txt"
- navbar:    "GitHub"
  link:      "https://github.com/Dimasichsanul/os212"
- navbar:    "GitHub Page"
  link:      "https://dimasichsanul.github.io/os212/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "TarBall"
  link:      "https://os.vlsm.org/Log/Dimasichsanul.tar.bz2.txt"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "Template Zip File"
  link:      "/template.zip"
title:       "Dimas Ichsanul's OS212 Github Page"
lang:        "en-US"
author:      "Dimas Ichsanul Arifin"
address:     "Depok"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://dimasichsanul.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/Dimasichsanul/os212"


